### ISSUE TITLE
passing features as weighting and summarizer parameters is done with heuristics

### ISSUE THREAD

**Issue by andreasbaumann** [patrickfrey/strusWebService#9] opened 2018-07-18 05:49 UTC
<a href="https://github.com/andreasbaumann"><img src="https://avatars2.githubusercontent.com/u/202930?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [andreasbaumann](https://github.com/andreasbaumann)**
_Saturday Apr 16, 2016 at 18:23 GMT_
_Originally opened as https://github.com/Eurospider/strusWebService/issues/9_

----

Currently we have a subtle logic how to find out whether a parameter has to be
passed as string/numeric parameter or as feature to a weighting or summarizer 
function:
- the parameter name exists in a location which is clearly expecting a feature
  (e. g. 'selection' is only accepting features)
- we take the desciption of the function as reference

**Comment by andreasbaumann** [comment] 2018-07-18 05:49
<a href="https://github.com/andreasbaumann"><img src="https://avatars2.githubusercontent.com/u/202930?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [andreasbaumann](https://github.com/andreasbaumann)**
_Saturday Apr 16, 2016 at 18:23 GMT_

----

the same applies for parameters expecting a term type (we check whether the term
type exists in the storage).

**Comment by patrickfrey** [comment] 2018-08-16 23:31
duplicate of an issue I do not understand

**Closed by patrickfrey** 2018-08-16 23:31 UTC
Labels: enhancement
